/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kobayashi-hiroaki' at '17/06/27 10:52' with Gradle 2.14
 *
 * @author kobayashi-hiroaki, @date 17/06/27 10:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
